package calcul;


/**
* calcul/calcul_montants.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/CHEDI/eclipse-workspace/CorbaTest/src/spec.idl
* Tuesday, December 7, 2021 11:38:48 PM CET
*/

public interface calcul_montants extends calcul_montantsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calcul_montants
