package calcul;


/**
* calcul/calcul_montantsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/CHEDI/eclipse-workspace/CorbaTest/src/spec.idl
* Tuesday, December 7, 2021 11:38:48 PM CET
*/

public interface calcul_montantsOperations 
{
  double calcul_ttc (double mt_ht, double taux);
} // interface calcul_montantsOperations
